name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /opt/doctors_workspace
            
            echo "=== Pulling latest code ==="
            git pull origin main
            
            echo "=== Stopping containers ==="
            docker compose -f docker-compose.prod.yml down
            
            echo "=== Building images ==="
            docker compose -f docker-compose.prod.yml build --no-cache
            
            echo "=== Starting containers ==="
            docker compose -f docker-compose.prod.yml up -d
            
            echo "=== Waiting for services to start ==="
            sleep 15
            
            echo "=== Checking container status ==="
            docker compose -f docker-compose.prod.yml ps
            
            echo "=== Deployment completed successfully ==="
      
      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful"
          else
            echo "❌ Deployment failed"
          fi

